### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SkewedZeppelin** [AmnestyTech/investigations#11]
This repository has no LICENSE file.
What are the IOCs licensed under?

I would like to add them to my FOSS real-time malware scanner app, Hypatia:
https://github.com/divested-mobile/hypatia

**Comment by Moejoe90** [comment]
Any updates?

**Comment by Te-k** [comment]
Hi, sorry for the delay, you can do pretty much what you want with the indicators as long as you mention where it is coming from, so that's CC-BY. I'll add it to the README.
