### ISSUE TITLE
False Indication of Pegasus

### ISSUE THREAD

**Issue by rick-rheo** [AmnestyTech/investigations#19]
For Pegasus detection (pegasus.stix2) the scan considers the mere presence of Library/Preferences/com.apple.CrashReporter.plist to be an indication of infection.  This raises a false flag on any iPhone used for normal iOS development.   You're looking for  

```
	<key>ShouldSubmit</key>
	<false/>
```

in the contents of that file as a more accurate indicator of Pegasus infection.    If the above is  

```
	<key>ShouldSubmit</key>
	<true/>  
```

that is normal for any iOS developer's iPhone.

**Comment by Te-k** [comment]
Hi,

This is indeed correct, but mvt does not check the content of the file, it only relies on the manifest file, so we have decided to keep this indicator that can be valuable and add a note in the IOC page https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso
