### ISSUE TITLE
How to delist a domain?

### ISSUE THREAD

**Issue by tons** [AmnestyTech/investigations#21]
Hi! I am a web developer and I need your help for a domain exclusion from you _investigation domains list_.

I found this project because an issue with a client's website that was blocked by ESET antivirus. Why? Because, they say that until my client's domain (**posta.news**) is on the list, they will not be able to white list that domain.

I have made a lot of changes, cleaning and scans; my client's website is clean, it is a simple _news wordpress website_; maybe some day in the past was dirty but it was not our intention. By the way, if you see and can provide me more info about where or what is in our website code, **please** let me know.

We really need your help, **thanks in advance**!

Regards!

**Comment by Te-k** [comment]
Hi,

Thanks for reaching out. We provide here indications of malicious activity at a certain time. In your case, this domain was used for malicious activity around 2017-2019, which is before you registered it for your client.
We are not responsible for blocking these domains, some people have blocked them without considering the time period in which these domains were used, you have to see with them directly (in that case ESET) to have them unblocked, there is not much we can do about it.
