### ISSUE TITLE
Error in SHA256 hash

### ISSUE THREAD

**Issue by arieljt** [AmnestyTech/investigations#3]
Hi,

The hash a890c88b6c64371242b4047830b9189b4546536c6b11576d0738f0ba1840ade is 63 character long, it's missing one character for a SHA256 hash.

Could you please fix it?

Thank you,
Ariel

**Comment by Te-k** [comment]
It is actually a890c88b6c64371242b4047830b9189b4546536c6b11576d0738f0ba1840aded, I just fixed it, thanks for catching it
