### ISSUE TITLE
Generating a complete list of all NSO Owned Domains for your  trusted ad-blocker

### ISSUE THREAD

**Issue by voidspacexyz** [AmnestyTech/investigations#4]
I use the following to generate a complete ad-block list from this amazing repository.

1. Clone the repo
2. ```cd investigations```
3. ```cat */*domains.txt | sort | uniq  | tee amensty_nso_domain_list.txt```

Now you can add ```amensty_nso_domain_list.txt``` to your trusted ad-blocker.

On a sidenote, we should possibly run this on every commit, so the request to the Amnesty team would be to see if this can configure as a job to keep either this/other repo updated with the latest list always ?

**Comment by voidspacexyz** [comment]
Here is what the final list would look like : https://raw.githubusercontent.com/voidspacexyz/amnesty_nso_domain_list/main/amensty_nso_domain_list.txt

**Comment by mutageneral** [comment]
We should get this added in popular blocklists.

**Comment by szedlakmate** [comment]
Please work together with adAway to be able to use this list in the app 🙏
https://adaway.org/

**Comment by ccuser44** [comment]
Im going to suggest to add this to uBlock Origin

**Comment by hcarrega** [comment]
You can add this list manually

**Comment by smashah** [comment]
I will be adding this to https://github.com/smashah/smashblock and it will be kept up to date with this repo thanks

**Comment by travisboss** [comment]
@voidspacexyz are you maintaining that list you linked initially?

**Comment by szedlakmate** [comment]
This PR should be a big step forward: https://github.com/AmnestyTech/investigations/pull/15

**Comment by travisboss** [comment]
I've compiled the `domains.txt` list to adguard syntax here: https://github.com/travisboss/Jefe-Lists/blob/main/pegasus_blocklist.txt. 

Will be following closely if anything changes on the repo.

**Comment by Te-k** [comment]
Hi, we think that there is little interest of doing so because domains are discarded by NSO as soon as they are published and they have in the past deployed a new infrastructure after each publication. So blocking these domains won't add much security for anyone

**Comment by spirillen** [comment]
> Hi, we think that there is little interest of doing so because domains are discarded by NSO as soon as they are published and they have in the past deployed a new infrastructure after each publication. So blocking these domains won't add much security for anyone

True, and a huge number of the records appears to be outdated anyway

![image](https://user-images.githubusercontent.com/44526987/127756873-36cdb913-6e5b-438e-81f2-7e134ad31b79.png)

**Comment by Te-k** [comment]
Indeed, these are old domains that are useful for the sake of research or identifying attacks through forensic, not for network security. I close this issue, feel free to reopen if something is not clear
