### ISSUE TITLE
MVT with STIX

### ISSUE THREAD

**Issue by amineds** [AmnestyTech/investigations#9]
Would you mind adding an indication how to pass the stix file to MVT command ?
It's not clear from MVT documentation how to do so.

**Comment by hazcod** [comment]
@amineds https://mvt.readthedocs.io/en/latest/ios/backup/check.html
You need to supply `-I/--iocs` to the `mvt check-backup` command.

**Comment by Te-k** [comment]
Thanks @hazcod , yes indeed, you need to use the `-i` `--iocs` command

**Comment by amineds** [comment]
Thanks @hazcod @Te-k it works fine
